[project]
name = "Library"
version = "1.0.0"
description = "某大学生的2025年秋季Python课程大作业之图书管理系统"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbutils>=3.1.2",
    "flask>=3.1.2",
    "requests>=2.32.5",
]
