[project]
name = "library-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbutils>=3.1.2",
    "flask>=3.1.2",
    "requests>=2.32.5",
]
